spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/mercadolivro
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: fe6da7bc-1240-43c8-9f10-98da18e46a48
  expiration: 9999999